DROP TABLE "Orders"
DROP TABLE "Customers"
DROP TABLE "Hoodies"

CREATE TABLE "Customers" (
  "customerId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(120) NOT NULL,
  "firstName" varchar(120) NOT NULL,
  "lastName" varchar(120) NOT NULL,
  "contactNumber" varchar(120) NOT NULL
);

CREATE TABLE "Orders" (
  "orderId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customerId" INT NOT NULL,
  "orderDate" date DEFAULT CURRENT_DATE,
  "totalPrice" float NOT NULL DEFAULT 1,
  "orderItems" jsonb[] NOT NULL 
);

CREATE TYPE "hoodieSize" AS ENUM ('small', 'medium', 'large');

CREATE TABLE "Hoodies" (
  "hoodieId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "price" float NOT NULL,
  "hoodieDetails" jsonb NOT NULL DEFAULT '{}',
  "hoodieSizes" "hoodieSize" NOT NULL DEFAULT 'medium'
);

ALTER TABLE "Orders" ADD FOREIGN KEY ("customerId") REFERENCES "Customers" ("customerId");