CREATE TABLE "Customers" (
  "customerId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(120) NOT NULL
);

CREATE TABLE "Orders" (
  "orderId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customerId" INT NOT NULL,
  "orderDate" timestamp DEFAULT CURRENT_TIMESTAMP,
      "totalPrice" float NOT NULL DEFAULT 1,
  "orderItems" jsonb[] NOT NULL DEFAULT '{}',
  "orderComplete" boolean NOT NULL DEFAULT false
);

CREATE TYPE "hoodieSize" AS ENUM ('small', 'medium', 'large');

CREATE TYPE "hoodieColor" AS ENUM ('red', 'blue', 'green', 'black', 'white', 'grey');

CREATE TABLE "Hoodies" (
  "hoodieId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "price" float NOT NULL,
  "color" "hoodieColor" NOT NULL DEFAULT 'black',
  "hoodieDetails" jsonb NOT NULL DEFAULT '{}',
  "hoodieSizes" "hoodieSize" NOT NULL DEFAULT 'medium'
);

ALTER TABLE "Orders" ADD FOREIGN KEY ("customerId") REFERENCES "Customers" ("customerId");